### ISSUE TITLE
Consider using superscript and subscript instead of math command

### ISSUE THREAD

**Issue by bwittman** [start-concurrent/start-concurrent.github.io#35]
The majority of the math presented in the textbook relies only on superscript and subscript as special formatting.  Should we user superscript and subscript commands instead of using the math commands (currently executed with `stem:[]` in most cases)?

The math commands format the text differently, which is needlessly jarring.  Perhaps math can simply be formatted to match the normal font better.

**Comment by jtkorb** [comment]
So that "latexmath:[k^{\mathrm{th}}]" becomes "_k_^th^".  In my test, yes, the font matches the running text much better.  I think we'll need to do this by hand, right?

I think the numbers would look better, too.  A lot of them are done in math mode, but would probably look better in the normal font.

Note that the auto-converted adoc files (chapters 2+) currently use latexmath: explicitly, rather than stem:.  I think I did this because latexmath and asciimath are not source compatible, so just setting it in the :stem: statement as though it were changeable is a bit misleading.

**Comment by bwittman** [comment]
Yeah, I phrased the issue badly: it's not just about superscripts and subscripts.  I agree that it has to be done by hand.

**Comment by bwittman** [comment]
Done.  The last pass through the book removed *all* stem directives.
