### ISSUE TITLE
Rewrite all cross references to remove colons

### ISSUE THREAD

**Issue by jtkorb** [start-concurrent/start-concurrent.github.io#56]

**Comment by jtkorb** [comment]
I've started on a program to do this.  Will also help with issue #57.

**Comment by bwittman** [comment]
No program may be necessary!  When we use AsciiDoctor the "right" way (linking to section names instead of creating explicit links), the colons we use in section names are automatically removed.

It seems like there are only a few explicit links that need to be cleaned up, and then links to websites and e-mail addresses also contain colons.
